fix echo summary issue

diff --git a/.github/workflows/run_bisect_on_repo.yml b/.github/workflows/run_bisect_on_repo.yml
--- a/.github/workflows/run_bisect_on_repo.yml
+++ b/.github/workflows/run_bisect_on_repo.yml
@@ -91,21 +91,20 @@ jobs:
 
     - name: Check the good commit
       run: |
-        checkout_result=$(git checkout ${{ github.event.inputs.good_commit }})
-        if [[ $? -ne 0 ]]; then
-          echo "The specified good commit:${{ github.event.inputs.good_commit }} is invalid in git history" >> $GITHUB_STEP_SUMMARY
-          exit 1
-        else
+        if git checkout ${{ github.event.inputs.good_commit }}; then
           echo "The specified good commit:${{ github.event.inputs.good_commit }} is valid in git history" >> $GITHUB_STEP_SUMMARY
-          #run bisect check bash here, if it is not valid, exit 1 and print the error message
+          # Run bisect check bash here, if it is not valid, exit 1 and print the error message
           if ! ./bisect_check.sh; then
-            echo "The specified good commit:${{ github.event.inputs.good_commit }} is invalid in the check command, means the input good commit is actually not good for you check command." >> $GITHUB_STEP_SUMMARY
+            echo "The specified good commit:${{ github.event.inputs.good_commit }} is invalid in the check command, which means the input good commit is actually not good for your check command." >> $GITHUB_STEP_SUMMARY
             git checkout -
             exit 1
           else
             echo "The specified good commit:${{ github.event.inputs.good_commit }} is valid in the check command." >> $GITHUB_STEP_SUMMARY
             git checkout -
           fi
+        else
+          echo "The specified good commit:${{ github.event.inputs.good_commit }} is invalid in git history" >> $GITHUB_STEP_SUMMARY
+          exit 1
         fi
 
     - name: Run bisect with check command bash
